import type {Metadata} from "next";
import "./globals.css";
import {Manrope} from "next/font/google";
import {AudioProvider} from "./context/AudioContext";
import {CountdownProvider} from "./context/CountdownContext";

const manrope = Manrope({
    subsets: ["latin"],
    // weight: ["400", "700"],
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={manrope.className}
        >
        <CountdownProvider>
            <AudioProvider>
                {children}
            </AudioProvider>
        </CountdownProvider>
        </body>
        </html>
    );
}
